name: macOS 11

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: brew install --cask vcv-rack
      - run: /Applications/VCV\ Rack\ 2\ Free.app/Contents/MacOS/Rack -h -t 1 <<< '\n'
      - run: cat ~/Documents/Rack2/log.txt
      - run: ls -lR ~/Documents/Rack2/
